const userNames = [
  "Aaran",
  "Aaren",
  "Aarez",
  "Aarman",
  "Aaron",
  "Aaron-James",
  "Aarron",
  "Aaryan",
  "Aaryn",
  "Aayan",
  "Aazaan",
  "Abaan",
  "Abbas",
  "Abdallah",
  "Abdalroof",
  "Abdihakim",
  "Abdirahman",
  "Abdisalam",
  "Abdul",
  "Abdul-Aziz",
  "Abdulbasir",
  "Abdulkadir",
  "Abdulkarem",
  "Smith",
  "Jones",
  "Coollastname",
  "enter_name_here",
  "Ze",
  "Zechariah",
  "Zeek",
  "Zeeshan",
  "Zeid",
  "Zein",
  "Zen",
  "Zendel",
  "Zenith",
  "Zennon",
  "Zeph",
  "Zerah",
  "Zhen",
  "Zhi",
  "Zhong",
  "Zhuo",
  "Zi",
  "Zidane",
  "Zijie",
  "Zinedine",
  "Zion",
  "Zishan",
  "Ziya",
  "Ziyaan",
  "Zohaib",
  "Zohair",
  "Zoubaeir",
  "Zubair",
  "Zubayr",
  "Zuriel",
  "Xander",
  "Jared",
  "Courtney",
  "Gillian",
  "Clark",
  "Jared",
  "Grace",
  "Kelsey",
  "Tamar",
  "Alex",
  "Mark",
  "Tamar",
  "Farish",
  "Sarah",
  "Nathaniel",
  "Parker",
];

const friends = [
  "Aaran2",
  "Aaren2",
  "Aarez2",
  "Aarman2",
  "Aaron2",
  "Aaron-James2",
  "Aarron2",
  "Aaryan2",
  "Aaryn2",
  "Aayan2",
  "Aazaan2",
  "Abaan2",
  "Abbas2",
  "Abdallah2",
  "Abdalroof2",
  "Abdihakim2",
  "Abdirahman2",
  "Abdisalam2",
  "Abdul2",
  "Abdul-Aziz2",
  "Abdulbasir2",
  "Abdulkadir2",
  "Abdulkarem2",
  "Smith2",
  "Jones2",
  "Coollastname2",
  "enter_name_here2",
  "Ze2",
  "Zechariah2",
  "Zeek2",
  "Zeeshan2",
  "Zeid2",
  "Zein2",
  "Zen2",
  "Zendel2",
  "Zenith2",
  "Zennon2",
  "Zeph2",
  "Zerah2",
  "Zhen2",
  "Zhi2",
  "Zhong2",
  "Zhuo2",
  "Zi2",
  "Zidane2",
  "Zijie2",
  "Zinedine2",
  "Zion2",
  "Zishan2",
  "Ziya2",
  "Ziyaan2",
  "Zohaib2",
  "Zohair2",
  "Zoubaeir2",
  "Zubair2",
  "Zubayr2",
  "Zuriel2",
  "Xander2",
  "Jared2",
  "Courtney2",
  "Gillian2",
  "Clark2",
  "Jared2",
  "Grace2",
  "Kelsey2",
  "Tamar2",
  "Alex2",
  "Mark2",
  "Tamar2",
  "Farish2",
  "Sarah2",
  "Nathaniel2",
  "Parker2",
];

// Get a random item given an array
const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

// Gets a random user name
const getRandomName = () => `${getRandomArrItem(userNames)}`;

// Function to generate random friends that we can add to user object.
const getRandomFriends = (int) => {
  const results = [];
  for (let i = 0; i < int; i++) {
    results.push({
      userNames: getRandomArrItem(friends),
      /*       score: Math.floor(Math.random() * (99 - 70 + 1) + 70),
       */
    });
  }
  return results;
};

// Export the functions for use in seed.js
module.exports = { getRandomName, getRandomFriends };
